---
- name: "configuration play." 
  hosts: web
  user: ubuntu
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_record_host_keys: false
    - ansible_stdout_callback: yaml
    #- ansible_ssh_common_args: '-o ProxyCommand="ssh -o StrictHostKeyChecking=no"'

  pre_tasks:
    - name: "wait 600 seconds for target connection to become reachable/usable."
      # Your code here
      wait_for_connection:
        timeout: 600

#    - name: "install python for Ansible."
#      # Your code here
#      raw: sudo apt-get -y install python3

  roles:
    # Your code here
    - configure-server